// Klempírna
export const klempirna = [
  {
    id: 1,
    speaker: "Manfrotto",
    category: "Přednáška",
    name: "Jak vybrat stativ a příslušenství",
    time: "10:15 - 11:15",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 2,
    speaker: "Sony",
    category: "Přednáška",
    name: "Síla Sony systému",
    time: "11:30 - 12:30",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 3,
    speaker: "Miloš Nejezchleb",
    category: "Přednáška",
    name: "Art fotografie",
    time: "12:45 - 13:45",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 4,
    speaker: "F22 - Michal Houdek",
    category: "Workshop",
    name: "Fotíme motorku prakticky",
    time: "14:30 - 15:30",
    hasRegistration: true,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 5,
    speaker: "Jiří Lízler",
    category: "Přednáška",
    name: "Marketing pro fotografy",
    time: "15:45 - 16:45",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 6,
    speaker: "FullFace - Martin Vrbický a Štěpán Romanov",
    category: "Přednáška",
    name: "Natáčení v outdooru",
    time: "17:00 - 18:00",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
];

// Ateliér
export const atelier = [
  {
    id: 1,
    speaker: "ViewSonic",
    category: "Přednáška",
    name: "Jak na barvy na monitoru",
    time: "10:30 - 11:30",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 2,
    speaker: "Tamron - Lukáš Szwejdar",
    category: "Workshop",
    name: "Glamour fotografie",
    time: "11:45 - 12:45",
    hasRegistration: true,
    isPaid: false,
    isFull: true,
    shopLink: "#",
  },
  {
    id: 3,
    speaker: "Canon",
    category: "Přednáška",
    name: "Novinky u Canonu",
    time: "13:00 - 14:00",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 4,
    speaker: "Petr Dudek",
    category: "Přednáška",
    name: "Portréty a svatby",
    time: "14:15 - 15:15",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 5,
    speaker: "Mayhempictures - Zbyněk Mach",
    category: "Přednáška",
    name: "Focení automotive",
    time: "15:30 - 16:30",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 6,
    speaker: "Milan Říský",
    category: "Přednáška",
    name: "Koncertní fotografie",
    time: "16:45 - 17:45",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 7,
    speaker: "Martin Koudela",
    category: "Přednáška",
    name: "Timelapse",
    time: "18:00 - 19:00",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
];

// Kontejnery
export const kontejnery = [
  {
    id: 1,
    speaker: "Tereza Václavová",
    category: "Přednáška",
    name: "Svatební focení - tipy a rady ",
    time: "10:00 - 11:00",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 2,
    speaker: "Radek Karko",
    category: "Přednáška",
    name: "Wildlife video, sport, Afrika",
    time: "11:30 - 12:30",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 3,
    speaker: "F22 - Michal Houdek",
    category: "Přednáška",
    name: "Jak fotit motorku",
    time: "12:45 - 13:45",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 4,
    speaker: "Kvalitní fotky - Petr Komárek",
    category: "Přednáška",
    name: "Systém pro fotografy",
    time: "14:00 - 15:00",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 5,
    speaker: "Leica Klub",
    category: "Přednáška",
    name: "Leica a vše kolem",
    time: "15:15 - 16:15",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 6,
    speaker: "Vojta Pollák",
    category: "Přednáška",
    name: "FPV drony",
    time: "17:00 - 18:00",
    hasRegistration: false,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
];

// Nádvoří
export const nadvori = [
  {
    id: 1,
    speaker: "Canon",
    category: "Workshop",
    name: "Portrét s Canonem",
    time: "10:00 - 11:30",
    hasRegistration: true,
    isPaid: true,
    isFull: false,
    shopLink:
      "https://www.phototools.cz/zbozi/portret-s-canonem-workshop-na-foto-fest-plzen/",
  },
  {
    id: 2,
    speaker: "Nikon - Filip Barták",
    category: "Workshop",
    name: "Photowalk s Nikonem",
    time: "11:45 - 12:45",
    hasRegistration: true,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 3,
    speaker: "Peakdesign - You&Me",
    category: "Workshop",
    name: "Fotky s příběhem",
    time: "11:45 - 12:45",
    hasRegistration: true,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 4,
    speaker: "Sony - Jan Tichý",
    category: "Workshop",
    name: "Zachyťte přirozený portrét se Sony",
    time: "14:00 - 15:00",
    hasRegistration: true,
    isPaid: true,
    isFull: false,
    shopLink:
      "https://www.phototools.cz/zbozi/zachytte-prirozeny-portret-se-sony-workshop-na-foto-fest-plzen-2022/",
  },
  {
    id: 5,
    speaker: "Manfrotto - Lukáš Navara",
    category: "Workshop",
    name: "Portréty",
    time: "15:30 - 16:30",
    hasRegistration: true,
    isPaid: false,
    isFull: true,
    shopLink: "#",
  },
  {
    id: 6,
    speaker: "Dominik Beránek",
    category: "Workshop",
    name: "Street portrét",
    time: "16:45 - 17:45",
    hasRegistration: true,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
  {
    id: 7,
    speaker: "Tomáš Košňar + Leica klub",
    category: "Workshop",
    name: "Focení na film",
    time: "18:00 - 19:00",
    hasRegistration: true,
    isPaid: false,
    isFull: false,
    shopLink: "#",
  },
];
