// Ateliér
export const atelier = [
  {
    id: 1,
    speaker: "Jméno Příjmení 1",
    category: "Přednáška",
    name: "Lorem ipsum dolor sit amet de elit?",
    time: "14:00 - 15:00",
    hasRegistration: false,
    isPaid: false,
    shopLink: "https://phototools.cz",
  },
  {
    id: 2,
    speaker: "Jméno Příjmení 2",
    category: "Workshop",
    name: "Lorem ipsum dolor sit amet de elit?",
    time: "14:00 - 15:00",
    hasRegistration: true,
    isPaid: false,
    shopLink: "https://phototools.cz",
  },
  {
    id: 3,
    speaker: "Jméno Příjmení 3",
    category: "Workshop",
    name: "Lorem ipsum dolor sit amet de elit?",
    time: "14:00 - 15:00",
    hasRegistration: true,
    isPaid: true,
    shopLink: "https://phototools.cz",
  },
  {
    id: 4,
    speaker: "Jméno Příjmení 4",
    category: "Přednáška",
    name: "Lorem ipsum dolor sit amet de elit?",
    time: "14:00 - 15:00",
    hasRegistration: false,
    isPaid: false,
    shopLink: "https://phototools.cz",
  },
  {
    id: 5,
    speaker: "Jméno Příjmení 5",
    category: "Přednáška",
    name: "Lorem ipsum dolor sit amet de elit?",
    time: "14:00 - 15:00",
    hasRegistration: false,
    isPaid: false,
    shopLink: "https://phototools.cz",
  },
  {
    id: 6,
    speaker: "Jméno Příjmení 6",
    category: "Přednáška",
    name: "Lorem ipsum dolor sit amet de elit?",
    time: "14:00 - 15:00",
    hasRegistration: false,
    isPaid: false,
    shopLink: "https://phototools.cz",
  },
  {
    id: 7,
    speaker: "Jméno Příjmení 7",
    category: "Přednáška",
    name: "Lorem ipsum dolor sit amet de elit?",
    time: "14:00 - 15:00",
    hasRegistration: false,
    isPaid: false,
    shopLink: "https://phototools.cz",
  },
  {
    id: 8,
    speaker: "Jméno Příjmení 8",
    category: "Přednáška",
    name: "Lorem ipsum dolor sit amet de elit?",
    time: "14:00 - 15:00",
    hasRegistration: false,
    isPaid: false,
    shopLink: "https://phototools.cz",
  },
];

// Klempírna
export const klempirna = [
  {
    id: 1,
    speaker: "Jméno Příjmení 1",
    category: "Přednáška",
    name: "Lorem ipsum dolor sit amet de elit?",
    time: "14:00 - 15:00",
    hasRegistration: false,
    isPaid: false,
    shopLink: "https://phototools.cz",
  },
  {
    id: 2,
    speaker: "Jméno Příjmení 2",
    category: "Workshop",
    name: "Lorem ipsum dolor sit amet de elit?",
    time: "14:00 - 15:00",
    hasRegistration: true,
    isPaid: false,
    shopLink: "https://phototools.cz",
  },
  {
    id: 3,
    speaker: "Jméno Příjmení 3",
    category: "Workshop",
    name: "Lorem ipsum dolor sit amet de elit?",
    time: "14:00 - 15:00",
    hasRegistration: true,
    isPaid: true,
    shopLink: "https://phototools.cz",
  },
  {
    id: 4,
    speaker: "Jméno Příjmení 4",
    category: "Přednáška",
    name: "Lorem ipsum dolor sit amet de elit?",
    time: "14:00 - 15:00",
    hasRegistration: false,
    isPaid: false,
    shopLink: "https://phototools.cz",
  },
  {
    id: 5,
    speaker: "Jméno Příjmení 5",
    category: "Přednáška",
    name: "Lorem ipsum dolor sit amet de elit?",
    time: "14:00 - 15:00",
    hasRegistration: false,
    isPaid: false,
    shopLink: "https://phototools.cz",
  },
  {
    id: 6,
    speaker: "Jméno Příjmení 6",
    category: "Přednáška",
    name: "Lorem ipsum dolor sit amet de elit?",
    time: "14:00 - 15:00",
    hasRegistration: false,
    isPaid: false,
    shopLink: "https://phototools.cz",
  },
];

// Nádvoří
export const nadvori = [
  {
    id: 1,
    speaker: "Jméno Příjmení 1",
    category: "Workshop",
    name: "Lorem ipsum dolor sit amet de elit?",
    time: "14:00 - 15:00",
    hasRegistration: true,
    isPaid: true,
    shopLink: "https://phototools.cz",
  },
  {
    id: 2,
    speaker: "Jméno Příjmení 2",
    category: "Workshop",
    name: "Lorem ipsum dolor sit amet de elit?",
    time: "14:00 - 15:00",
    hasRegistration: true,
    isPaid: false,
    shopLink: "https://phototools.cz",
  },
  {
    id: 3,
    speaker: "Jméno Příjmení 3",
    category: "Workshop",
    name: "Lorem ipsum dolor sit amet de elit?",
    time: "14:00 - 15:00",
    hasRegistration: true,
    isPaid: false,
    shopLink: "https://phototools.cz",
  },
  {
    id: 4,
    speaker: "Jméno Příjmení 4",
    category: "Přednáška",
    name: "Lorem ipsum dolor sit amet de elit?",
    time: "14:00 - 15:00",
    hasRegistration: false,
    isPaid: false,
    shopLink: "https://phototools.cz",
  },
];

// Kontejnery
export const kontejnery = [
  {
    id: 1,
    speaker: "Jméno Příjmení 1",
    category: "Přednáška",
    name: "Lorem ipsum dolor sit amet de elit?",
    time: "14:00 - 15:00",
    hasRegistration: false,
    isPaid: false,
    shopLink: "https://phototools.cz",
  },
  {
    id: 2,
    speaker: "Jméno Příjmení 2",
    category: "Workshop",
    name: "Lorem ipsum dolor sit amet de elit?",
    time: "14:00 - 15:00",
    hasRegistration: true,
    isPaid: false,
    shopLink: "https://phototools.cz",
  },
  {
    id: 3,
    speaker: "Jméno Příjmení 3",
    category: "Workshop",
    name: "Lorem ipsum dolor sit amet de elit?",
    time: "14:00 - 15:00",
    hasRegistration: true,
    isPaid: true,
    shopLink: "https://phototools.cz",
  },
  {
    id: 4,
    speaker: "Jméno Příjmení 4",
    category: "Přednáška",
    name: "Lorem ipsum dolor sit amet de elit?",
    time: "14:00 - 15:00",
    hasRegistration: false,
    isPaid: false,
    shopLink: "https://phototools.cz",
  },
  {
    id: 5,
    speaker: "Jméno Příjmení 5",
    category: "Přednáška",
    name: "Lorem ipsum dolor sit amet de elit?",
    time: "14:00 - 15:00",
    hasRegistration: false,
    isPaid: false,
    shopLink: "https://phototools.cz",
  },
  {
    id: 6,
    speaker: "Jméno Příjmení 6",
    category: "Workshop",
    name: "Lorem ipsum dolor sit amet de elit?",
    time: "14:00 - 15:00",
    hasRegistration: true,
    isPaid: true,
    shopLink: "https://phototools.cz",
  },
];
